### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by cmr** [kstep/rust-mpd#2]
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback, and has protections from
patent trolls and an explicit contribution licensing clause. However, the
Apache license is incompatible with GPLv2. This is why Rust is dual-licensed as
MIT/Apache (the "primary" license being Apache, MIT only for GPLv2 compat), and
doing so would be wise for this project. This also makes this crate suitable
for inclusion in the Rust standard distribution and other project using dual
MIT/Apache.

# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright) and then add the following to
your README:

```
## License

Licensed under either of
 * Apache License, Version 2.0 ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)
at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, use the following boilerplate (based on that used in Rust):

```
// Copyright (c) 2015 t developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.
```

And don't forget to update the `license` metadata in your `Cargo.toml`!

# Contributor checkoff

 - [x] @kstep

**Comment by kstep** [comment]
@cmr I don't like license headers in source files, so I haven't added them now. Otherwise I did everything to relicense in 1b114088e945020f1b279df8c5a705e3ef85f37c. Does it work for you, or I should add license headers to all source files?

**Comment by cmr** [comment]
I won't make official recommendation either way besides what's widely used and recommended in the license, but personally I don't think license headers add much if anything.

**Comment by kstep** [comment]
Ok, then official part:

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kstep** [comment]
FWIW, I made a script to relicense, to automate process for all my projects: https://gist.github.com/kstep/f9f99cca7ae9cc3d2e16

**Comment by cmr** [comment]
@kstep beware that the MIT license downloaded from the Rust repo there has the Rust Project Developers listed as the copyright, which you likely want to change.

**Comment by kstep** [comment]
@cmr thanks for pointing it out! I missed this point.
