### ISSUE TITLE
Why has this crate been dropped from crates.io?

### ISSUE THREAD

**Issue by czipperz** [kstep/rust-mpd#3]
I couldn't find any useful information about it.

**Comment by kstep** [comment]
I'm sorry. It was done by mistake during one of experiments with Cargo. I will republish it today.

**Comment by czipperz** [comment]
No problem! Thanks

**Comment by kstep** [comment]
I was hit by the https://github.com/rust-lang/crates.io/issues/76 issue.
I republished the crate under another version.
