### ISSUE TITLE
Query: cannot move out of `query` because it is borrowed

### ISSUE THREAD

**Issue by cornerman** [kstep/rust-mpd#4]
I am trying to query the mpd server for songs, but I have a problem with the borrow checker. When I try the following code snippet, the compiler complains. In your [corresponding testcase](https://github.com/kstep/rust-mpd/blob/master/tests/search.rs), you have commented out this part. So, how can I add filters to the query object?

**Code:**

```
extern crate mpd;

use mpd::Client;
use mpd::search::Term;
use std::env;

fn main() {
    let mut conn = Client::connect("localhost:6600").unwrap();
    let mut query = conn.query();
    query.limit(0, 2);
    let res = query.find(false, false);
    println!("{:?}", res);
}
```

**Compiler says:**

```
main.rs:11:15: 11:20 error: cannot move out of `query` because it is borrowed [E0505]
main.rs:11     let res = query.find(false, false);
                         ^~~~~
main.rs:10:5: 10:10 note: borrow of `query` occurs here
main.rs:10     query.limit(0, 2);
```

 If I leave out the line `query.limit(0, 2)`, I get an error from mpd: `Err(Server(ServerError { code: Argument, pos: 0, command: "find", detail: "too few arguments for \"find\"" }))`. Shouldn't this return all songs?

**Comment by kstep** [comment]
Database query API is not finished yet. It's not your fault, it's just not working. Sorry.

**Comment by cornerman** [comment]
Thanks for the response. We want to write a small mpc in rust and therefore depend on your library. Are you still planning on implementing the query interface? Are there any other missing feature we need to look out for? If you like, we could try to help in implementing missing pieces.

**Comment by kstep** [comment]
I'm a little distracted from the project at the moment. The library was for my home use, a hobby project to work in free time, so I wasn't aware it will get such high attention. It's a pleasure to know my work is really useful, thank you! Sure, I had some plans to implement missing bits.

From what I remember, database query API is the only big thing missing (the `search` module, which includes `find`, `search` and `list` families of MPD commands). I should have created issues here, but I was too lazy, my bad.

The story is, I wanted to provide a good unified API for all music database access, but I couldn't think of a general and ergonomic solution when I was at it. So I just took a break to think about the API better (and to get more Rust experience as well, as I was writing Rust code for relatively small time when I was working on the crate). Then I got distracted by other projects, new job and real life, so I haven't got back to it. Maybe now is the good time to implement missing bits.

And sure, you are very welcome to post PRs! I will be very glad to get any help. Thank you!

**Comment by kstep** [comment]
For the record, now I envision a unified `Query` structure independent of `Client`, which will be effectively a builder for any database query, so `Client` will have `search`, `list` and `count` methods with the `fn foo(&mut self, q: &Query) -> Result<Vec<T>>` signature, so crate user will be able to build  a query and run it with a client, like this: `client.search(Query::filter("term").offset(10).count(5))`.

**Comment by cornerman** [comment]
Sorry for the late response; your idea looks good to me!

I think, it would be good to have different methods for ```find``` and ```findadd``` because the latter does not require to retrieve the whole list of results from the server prior to adding them to a playlist or the queue. Do you think, it makes sense to have separate methods for ```find``` and ```search``` or should there be a fuzzy property in the Query struct? Also, do you know whether there is something like ```searchadd``` in mpd?

**Comment by kstep** [comment]
There is indeed searchadd command (http://www.musicpd.org/doc/protocol/database.html).
And as search and find command families are essentially duplicate each other, I'm more inclided to join them up into a single method.

As for findadd method, I'm not sure about it. Maybe a single find method with "add: bool" argument would be better? What do you think?

Also, it seems I'm going to be rather busy these days, as I have a lot of work on my day job, as well as a lot of things to arrange to the Minsk Rust meetup, so if you want to help me with this functionality, I would be very grateful to accept your PRs.

**Comment by cornerman** [comment]
Thanks! Yeah, joining search and find seems like the best option then. Though, I am not totally about findadd/searchadd, as the command really has a different signature: it does not return the result set. Nevertheless, I think I can create a PR from here and then we can discuss details :)

**Comment by tomprince** [comment]
This looks like it has been addressed?
