### ISSUE TITLE
[Potential bug found] cannot borrow `xxx` as mutable more than once at a time when using mpd's Query::and

### ISSUE THREAD

**Issue by CoorFun** [kstep/rust-mpd#40]
Hello,

Please refer to my stackover flow question. The first answer found a potential bug.

https://stackoverflow.com/questions/58878192/cannot-borrow-xxx-as-mutable-more-than-once-at-a-time-when-using-mpds-query/58879004#58879004

**Comment by SimonPersson** [comment]
I created a PR to fix this: #47.
