### ISSUE TITLE
Issue with client.status()

### ISSUE THREAD

**Issue by bchretien** [kstep/rust-mpd#5]
I noticed that the tests failed locally when fetching mpd status, i.e. this:
```rust
let mut c = Client::new(TcpStream::connect("127.0.0.1:6600").unwrap()).unwrap();
println!("version: {:?}", c.version);
println!("status: {:?}", c.status());
```
returns:
> version: Version(0, 19, 0)
> status: Err(Parse(BadPair))

The problem seems to be associated with [this line](https://github.com/kstep/rust-mpd/blob/cb30c80b889010e950788a6e1e88241c55b5071e/src/client.rs#L80):

```rust
// Playback options & status {{{
/// Get MPD status
pub fn status(&mut self) -> Result<Status> {
    self.run_command("command_list_begin")
        .and_then(|_| self.run_command("status"))
        .and_then(|_| self.run_command("replay_gain_status")) // <--- here
        .and_then(|_| self.run_command("command_list_end"))
        .and_then(|_| self.read_struct())
}
```
as removing it solves my problem.

Tested on Arch Linux, with rust-mpd cb30c80b889010e950788a6e1e88241c55b5071e , Rust 1.9.0 and mpd 0.19.15.

**Comment by kstep** [comment]
Could you please run the following commands with telnet and show me output:

- `commands`
- `replay_gain_status`

To do it, run `telnet 127.0.0.1 6600`, then enter each command and press `Enter`.

Thank you!

**Comment by bchretien** [comment]
Oh I didn't realize mpd provided a telnet console!

* `commands`:
```txt
commands
command: add
command: addid
command: addtagid
command: channels
command: clear
command: clearerror
command: cleartagid
command: close
command: commands
command: consume
command: count
command: crossfade
command: currentsong
command: decoders
command: delete
command: deleteid
command: disableoutput
command: enableoutput
command: find
command: findadd
command: list
command: listall
command: listallinfo
command: listfiles
command: listmounts
command: listneighbors
command: listplaylist
command: listplaylistinfo
command: listplaylists
command: load
command: lsinfo
command: mixrampdb
command: mixrampdelay
command: mount
command: move
command: moveid
command: next
command: notcommands
command: outputs
command: password
command: pause
command: ping
command: play
command: playid
command: playlist
command: playlistadd
command: playlistclear
command: playlistdelete
command: playlistfind
command: playlistid
command: playlistinfo
command: playlistmove
command: playlistsearch
command: plchanges
command: plchangesposid
command: previous
command: prio
command: prioid
command: random
command: rangeid
command: readmessages
command: rename
command: repeat
command: replay_gain_mode
command: replay_gain_status
command: rescan
command: rm
command: save
command: search
command: searchadd
command: searchaddpl
command: seek
command: seekcur
command: seekid
command: sendmessage
command: setvol
command: shuffle
command: single
command: stats
command: status
command: stop
command: subscribe
command: swap
command: swapid
command: tagtypes
command: toggleoutput
command: unmount
command: unsubscribe
command: update
command: urlhandlers
command: volume
OK
```

* `replay_gain_status`:

```txt
replay_gain_status
off
OK
```

**Comment by kstep** [comment]
Ok, now I see the problem.

My MPD instance gives a little different answer to `replay_gain_status` output is a little different:

```
replay_gain_status
replay_gain_mode: off
OK
```

My protocol version is 0.19.0, my MPD version is 0.19.15.

Could you please provide mpd.conf configuration file, just to compare our configs?

**Comment by bchretien** [comment]
Ok, I think I'm starting to understand what's going on... I am actually using [mopidy](https://github.com/mopidy/mopidy). After turning mopidy off and using the system's mpd service directly, I do get the proper behavior (`replay_gain_mode: off`). It seems that they reimplemented the mpd protocol, but apparently wrongly for that specific command ([j'accuse!](https://github.com/mopidy/mopidy/blob/20ba1fd90e81939a0da8a543d3e8bbb8472e9765/mopidy/mpd/protocol/playback.py#L318-L328)). So `rust-mpd` works just as expected. Sorry for the waste of time, and kudos for your work! I'll open a PR for mopidy ;)
