### ISSUE TITLE
No support for authentication with password

### ISSUE THREAD

**Issue by auroraanna** [kstep/rust-mpd#73]
This library does not support specifying a password for the connection. MPD can be configured to only allow some actions with a password.

**Comment by naglis** [comment]
@auroraanna it does, try calling [`client.login("<your-password>")`](http://kstep.me/rust-mpd/mpd/client/struct.Client.html#method.login) before issuing actions that require a password.

**Comment by auroraanna** [comment]
oh well, i only searched for "auth…"
