### ISSUE TITLE
Event on idle queue triggers twice

### ISSUE THREAD

**Issue by tsuflux** [kstep/rust-mpd#8]
I am trying to replicate the behaviour of the following command

```sh
while : ; do mpc idle player ; done
```

by using:

```rust
extern crate mpd;

use mpd::Idle;

fn main() {
    let mut conn = mpd::Client::connect("127.0.0.1:6600").unwrap();
    loop {
        let _ = conn.wait(&[mpd::Subsystem::Player]);
        println!("player");
    }
}
```

When I call for example `mpc next` the Rust variant however will often print out `player` twice while mpc behaves as expected.

**Comment by tomprince** [comment]
If I run `mpc idleloop player` or your example program, I get two notifications when the song switches via a song ending. I think this is just the expected behavior mpd.

**Comment by kstep** [comment]
If so, I close the issue.

**Comment by tsuflux** [comment]
Well, that is odd. `mpc idle` used to work just fine. But the problem can be worked around by using:

    while : ; do mpc idle player; sleep 1 ; done

So, it seems like this is a bug in MPD. The event on the queue is not deleted atomically such that resubscribing quickly will yield the same event again.
