### ISSUE TITLE
Switch from rustc-serialize to serde

### ISSUE THREAD

**Issue by matthiasbeyer** [kstep/rust-mpd#9]
Serde is where the things happen today, so it would be awesome to switch to serde here.

**Comment by kstep** [comment]
I'd wait for proc_macro to stabilize (it should be stabilized in Rust 1.15.0), so we can use stable Rust.

**Comment by tomprince** [comment]
Now that 1.15 is out with proc_macro, I've started on an implementation [here](https://github.com/kstep/rust-mpd/compare/master...tomprince:wip-serde). There are still a few helpers that should be moved somewhere more sensible.

I'm not sure if that implementation is compatible with the current output format ... the serialization isn't used internally, so I'm not sure what the intended usage is.
